### ISSUE TITLE
Deleted How-To articles still appear online and in the search results

### ISSUE THREAD

**Issue by ReneeRendon** [deconst/content-service#107]
Deleted How-To articles still appear online and in the search results.

(This was part of Issue #91 : Search issues on How-To site)

**Comment by smashwilson** [comment]
Until recently (earlier this week to be precise), _any_ deleted content would still appear online unless I deleted it individually by hand. Now that the build is using bulk uploads, deleted envelopes should finally be removed from the content service and search index. Until I get to #93, requests for those content IDs may still succeed because the content is still being served from the old Cloud Files container. If you really need something gone before then I can delete it from Cloud Files by hand.

Isn't the how-to site still using a custom Google search?

**Comment by smashwilson** [comment]
I cut the Cloud Files fetch and shipped the change this morning: deleted articles should no longer be online.

They'll likely still appear in search results because the how-to site doesn't use a Deconst search. (I might need to reindex manually, too.)

**Comment by ReneeRendon** [comment]
I am closing this issue. Now that we can access the Google Search Console, the How-To team will work on the fix.
